title: '{ :awestruct }'
description: Awestruct is a static site baking and deployment tool
gem_version: 0.5.6
#gem_pre_version: 0.5.6.beta9

asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    'prewrap!': ''

profiles:
  development:
    deploy: nil
  staging:
    base_url: http://staging.awestruct.org/
    deploy:
      host: awestruct.org
      path: /var/www/domains/awestruct.org/staging/htdocs/ 
      uncommitted: true
  github:
    base_url: http://awestruct.github.com/awestruct.org/
    deploy:
      host: github_pages
      uncommitted: true
  production:
    base_url: http://awestruct.org/
    minify: true
    deploy:
      host: awestruct.org
      path: /var/www/domains/awestruct.org/www/htdocs/ 
      uncommitted: true

intense_debate_acct: fa224495874e8d96bbf6f2dbcc26dac5
flattr_username: bobmcwhirter
