title: Awestruct
gem_version: 0.4.8


profiles:
  development:
  staging:
    base_url: http://staging.awestruct.org/
    deploy:
      host: awestruct.org
      path: /var/www/domains/awestruct.org/staging/htdocs/ 
  github:
    base_url: http://awestruct.github.com/awestruct.org/
    deploy:
      host: github_pages
  production:
    base_url: http://awestruct.org/
    deploy:
      host: awestruct.org
      path: /var/www/domains/awestruct.org/www/htdocs/ 

intense_debate_acct: fa224495874e8d96bbf6f2dbcc26dac5
flattr_username: bobmcwhirter
