title: '{ :awestruct }'
description: Awestruct is a static site baking and deployment tool
gem_version: 0.6.4
#gem_pre_version: 0.5.6.beta9

asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    'prewrap!': ''

profiles:
  development:
    deploy: nil
  github:
    base_url: https://awestruct.github.io/
    deploy:
      host: github_pages
      uncommitted: true

intense_debate_acct: fa224495874e8d96bbf6f2dbcc26dac5
flattr_username: bobmcwhirter
